name: main

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests
      run: |
        coverage run --source=src/services -m unittest
        coverage xml

    - name: Upload Coverage XML
    uses: actions/upload-artifact@v2
    with:
      name: coverage-xml
      path: coverage.xml


  analyze_sonar:
    needs: test
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/Sonar.yml
    secrets: inherit

  docker_deploy:
    needs: test
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
