name: main

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  analyze_sonar:
    # needs: test
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/Sonar.yml
    secrets: inherit
