name: main

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  analyze_sonar:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/Sonar.yml
    secrets: inherit

  docker_deploy:
    if: ${{ github.ref_name == 'main' }}
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
